### ISSUE TITLE
commenti

### ISSUE THREAD

**Issue by marte-git** [LucaMorazzano/XHTML-CSS-rappresentativo-1-#1]
sistemate gli indirizzi che si riferiscono ad lweb.
Mettete qualche commento in piu'nel readme sulle strutture che avete usato.
Nel readme mette i riferimenti ad entrambi (nome e istallazione su lweb)

**Comment by marte-git** [comment]
e inoltre, magari fate un sito con diverse pagine.

**Comment by LucaMorazzano** [comment]
Aggiunte pagine.
Sistemati riferimenti ad account lweb.
Aggiunte informazioni file README.
Effettuata validazione w3c.
